### ISSUE TITLE
Tags no readme.md

### ISSUE THREAD

**Issue by NKKFu** [maykbrito/covid-19#3]
Boa tarde. Estou mexendo no github e faz um tempo que eu tenho essa dúvida: o que são essas tags _(e como fazê-las)_ em baixo da descrição dos projetos?

![Screenshot_1](https://user-images.githubusercontent.com/59903312/82733474-0c3ba980-9ce2-11ea-8b31-b32444136f73.png)

Achei elas interessantes mas não sei o nome delas e nem como fazer 🤔

**Comment by maykbrito** [comment]
Opa. Vi no site shields.io

**Comment by NKKFu** [comment]
Valeu @maykbrito !
